using Microsoft.EntityFrameworkCore;
using eShoes.Models;

namespace eShoes.Context
{
    public class eShoesDbContext : DbContext
    {
        public DbSet<Product> Products { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<CartItem> CartItems { get; set; }

        public eShoesDbContext(DbContextOptions<eShoesDbContext> options) : base(options) { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
    
            modelBuilder.Entity<Cart>()
                .HasMany(c => c.Items)
                .WithOne(ci => ci.Cart)
                .HasForeignKey(ci => ci.CartId)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<Product>().HasData(
                new Product { Id = 1,  Name = "Nike Dunk Low",        Brand = "nike-filter",  Price = 899.99M,  Rating = 5, ImagePath = "/images/nikedunklow.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "The Nike Dunk Low is a timeless basketball-inspired sneaker with a low-top design, premium leather construction, and iconic color blocking for a classic streetwear look." },
                new Product { Id = 2,  Name = "Puma Smash V2",            Brand = "puma-filter",  Price = 229.99M,  Rating = 4, ImagePath = "/images/pumasmash.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Smash V2 offers a retro tennis shoe aesthetic with a sleek vulcanized sole, suede upper, and signature Formstrip branding for casual everyday wear." },
                new Product { Id = 3,  Name = "Asics Shogun 5",           Brand = "asics-filter", Price = 299.99M,  Rating = 5, ImagePath = "/images/asicsshogun.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Shogun 5 is a lightweight volleyball shoe featuring breathable mesh, shock-absorbing midsole, and non-marking rubber outsole for superior court performance." },
                new Product { Id = 4,  Name = "Mizuno Wave Mirai 5",      Brand = "mizuno-filter",Price = 219.99M,  Rating = 3, ImagePath = "/images/mizunowave5.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Wave Mirai 5 running shoes combine responsive cushioning with a breathable mesh upper and Wave plate technology for smooth transitions during runs." },
                new Product { Id = 5,  Name = "Nike Air Max",             Brand = "nike-filter",  Price = 319.99M,  Rating = 5, ImagePath = "/images/nikeairmax.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Nike Air Max features visible Air cushioning in the heel for unbelievable comfort, with a lightweight mesh upper and durable outsole for all-day wear." },
                new Product { Id = 6,  Name = "Puma Speedcat OG",         Brand = "puma-filter",  Price = 799.99M,  Rating = 5, ImagePath = "/images/pumaspeed.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Speedcat OG is a motorsport-inspired shoe with a low-profile design, sleek synthetic upper, and grippy rubber outsole for a racing-inspired look." },
                new Product { Id = 7,  Name = "Asics Upcourt 6",          Brand = "asics-filter", Price = 399.99M,  Rating = 4, ImagePath = "/images/asicsup.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Upcourt 6 volleyball shoes offer excellent grip and flexibility with a gum rubber outsole and breathable mesh upper for optimal court performance." },
                new Product { Id = 8,  Name = "Nike Downshifter",         Brand = "nike-filter",  Price = 304.99M,  Rating = 4, ImagePath = "/images/nikedownshifter.svg", Description = "Nike Downshifter running shoes provide lightweight cushioning with a breathable mesh upper and flexible outsole for natural movement during daily runs." },
                new Product { Id = 9,  Name = "Asics Gel-Equation 13",    Brand = "asics-filter", Price = 183.99M,  Rating = 2, ImagePath = "/images/asicsgel.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Gel-Equation 13 offers rearfoot GEL cushioning system and removable sockliner for comfortable support during walking or light running activities." },
                new Product { Id = 10, Name = "Mizuno Neo Vista",         Brand = "mizuno-filter",Price = 1199.99M, Rating = 5, ImagePath = "/images/mizunoneovista.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Neo Vista is a premium running shoe with Wave Plate technology, U4ic midsole for cushioning, and smooth ride engineering for marathon runners." },
                new Product { Id = 11, Name = "Puma Wired Run",           Brand = "puma-filter",  Price = 239.99M,  Rating = 5, ImagePath = "/images/pumawired.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Wired Run features a knit upper for breathability, cushioned midsole for comfort, and rubber outsole for traction in a modern running silhouette." },
                new Product { Id = 12, Name = "Nike Gamma Force",         Brand = "nike-filter",  Price = 449.99M,  Rating = 3, ImagePath = "/images/nikegammaforce.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Nike Gamma Force combines retro basketball aesthetics with modern comfort, featuring a padded collar, Air cushioning, and durable leather upper." },
                new Product { Id = 13, Name = "Puma Runner City",         Brand = "puma-filter",  Price = 259.99M,  Rating = 5, ImagePath = "/images/pumarunner.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Runner City blends retro running style with contemporary comfort, featuring a mesh and suede upper with cushioned midsole for urban exploration." },
                new Product { Id = 14, Name = "Asics Gel-NYC",            Brand = "asics-filter", Price = 899.99M,  Rating = 5, ImagePath = "/images/asicsnyc.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Gel-NYC is a premium running shoe with FF BLAST cushioning, GEL technology, and breathable mesh upper designed for long-distance comfort." },
                new Product { Id = 15, Name = "Nike Court Royale",        Brand = "nike-filter",  Price = 322.99M,  Rating = 4, ImagePath = "/images/nikecourtroyale.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Nike Court Royale is a clean, minimalist tennis-inspired sneaker with a leather upper, stitched overlays, and classic vulcanized sole for casual wear." },
                new Product { Id = 16, Name = "Mizuno Cool Ride",         Brand = "mizuno-filter",Price = 254.99M,  Rating = 4, ImagePath = "/images/mizunocoolride.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Cool Ride features breathable air mesh upper with Dynamotion Fit for flexibility and U4ic midsole for responsive cushioning during runs." },
                new Product { Id = 17, Name = "Mizuno Wave Prophecy",     Brand = "mizuno-filter",Price = 999.99M,  Rating = 5, ImagePath = "/images/mizunoprophecy.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Wave Prophecy running shoes feature Infinity Wave plate for ultimate cushioning and energy return, designed for neutral runners seeking premium performance." },
                new Product { Id = 18, Name = "Mizuno Wave Dynasty-6",    Brand = "mizuno-filter",Price = 329.99M,  Rating = 4, ImagePath = "/images/mizunodynasty.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Wave Dynasty 6 is a badminton shoe with Wave plate technology, non-marking rubber sole, and lightweight construction for quick court movements." },
                new Product { Id = 19, Name = "Puma Flyer Runner",        Brand = "puma-filter",  Price = 229.99M,  Rating = 3, ImagePath = "/images/pumaflyer.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Flyer Runner combines retro styling with modern comfort, featuring a mesh and synthetic upper with cushioned midsole for casual everyday wear." },
                new Product { Id = 20, Name = "Nike Air Jordan",          Brand = "nike-filter",  Price = 1499.99M, Rating = 5, ImagePath = "/images/nikeairjordan.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Air Jordan is the iconic basketball sneaker line featuring Air cushioning, premium materials, and timeless designs that revolutionized footwear culture." },
                new Product { Id = 21, Name = "Mizuno Wave Prophecy 14 S",Brand = "mizuno-filter",Price = 1799.99M, Rating = 5, ImagePath = "/images/mizuno14s.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Wave Prophecy 14 S offers next-level running technology with Infinity Wave plate, U4icX midsole, and breathable mesh for elite-level cushioning." },
                new Product { Id = 22, Name = "Asics Gel-Nimbus",         Brand = "asics-filter", Price = 1199.99M, Rating = 4, ImagePath = "/images/asicsnimbus.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Gel-Nimbus is a premium neutral running shoe with FF BLAST PLUS cushioning, GEL technology, and breathable knit upper for long-distance comfort." },
                new Product { Id = 23, Name = "Puma X-Ray",               Brand = "puma-filter",  Price = 349.99M,  Rating = 5, ImagePath = "/images/puma.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma X-Ray features a futuristic design with transparent rubber details, mesh upper for breathability, and cushioned midsole for street-ready comfort." },
                new Product { Id = 24, Name = "Nike MC Trainer",          Brand = "nike-filter",  Price = 379.99M,  Rating = 4, ImagePath = "/images/nikemctrainer.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Nike MC Trainer combines cross-training functionality with retro basketball aesthetics, featuring multi-directional traction and durable leather upper." },
                new Product { Id = 25, Name = "Mizuno Mxr",               Brand = "mizuno-filter",Price = 699.99M,  Rating = 5, ImagePath = "/images/mizunomxr.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno MXR is a high-performance running shoe with Wave plate technology, U4ic midsole, and breathable mesh upper for responsive cushioning." },
                new Product { Id = 26, Name = "Asics Japan S",            Brand = "asics-filter", Price = 317.99M,  Rating = 4, ImagePath = "/images/asicsjp.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Japan S is a heritage-inspired sneaker with premium suede and mesh upper, GEL cushioning, and vulcanized sole for casual lifestyle wear." },
                new Product { Id = 27, Name = "Nike Revolution 7",        Brand = "nike-filter",  Price = 284.99M,  Rating = 4, ImagePath = "/images/nikerevolution7.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Nike Revolution 7 offers lightweight cushioning with soft foam midsole, breathable mesh upper, and durable rubber outsole for everyday running comfort." },
                new Product { Id = 28, Name = "Mizuno Space 4",           Brand = "mizuno-filter",Price = 279.99M,  Rating = 5, ImagePath = "/images/mizunospace.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Mizuno Space 4 is a versatile running shoe with smooth ride engineering, breathable air mesh upper, and responsive U4ic midsole cushioning." },
                new Product { Id = 29, Name = "Asics Gel-Impression 11",  Brand = "asics-filter", Price = 249.99M,  Rating = 4, ImagePath = "/images/asicsimpr.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Gel-Impression 11 provides reliable support and cushioning with Rearfoot GEL technology and removable sockliner for comfortable all-day wear." },
                new Product { Id = 30, Name = "Puma Suede",               Brand = "puma-filter",  Price = 549.99M,  Rating = 3, ImagePath = "/images/pumasuede.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Suede is an iconic lifestyle sneaker featuring a soft suede upper, Formstrip branding, and cushioned sole for timeless streetwear style." },
                new Product { Id = 31, Name = "Asics Gel-Kayano Senna",   Brand = "asics-filter", Price = 1399.99M, Rating = 5, ImagePath = "/images/asicskay.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "ASICS Gel-Kayano Senna is a limited edition running shoe honoring Ayrton Senna, featuring FF BLAST cushioning and premium details for collectors." },
                new Product { Id = 32, Name = "Puma Shuffle BDP",         Brand = "puma-filter",  Price = 309.99M,  Rating = 4, ImagePath = "/images/pumashuffle.svg", AvailableSizes = "38, 39, 40, 42, 44", Description = "Puma Shuffle BDP combines skate shoe durability with streetwear style, featuring a suede and canvas upper with cushioned midsole for all-day comfort." }
            );   
        }
    }
}
